services:
  traefik:
    ports:
      - "443:443"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - ./traefik/acme.json:/letsencrypt/acme.json
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"

  live-documents-frontend:
    labels:
      - "traefik.http.routers.live-docs.entrypoints=websecure"
      - "traefik.http.routers.live-docs.tls.certresolver=letsencrypt"

  contact-api:
    labels:
      - "traefik.http.routers.contact-api.entrypoints=websecure"
      - "traefik.http.routers.contact-api.tls.certresolver=letsencrypt"

  root-site:
    labels:
      - "traefik.http.routers.root.entrypoints=websecure"
      - "traefik.http.routers.root.tls.certresolver=letsencrypt"

  live-documents-backend:
    environment:
      - Cors:Origins=["https://${DOMAIN}"]
    labels:
      - "traefik.http.routers.live-docs-api.entrypoints=websecure"
      - "traefik.http.routers.live-docs-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.live-docs-hubs.entrypoints=websecure"
      - "traefik.http.routers.live-docs-hubs.tls.certresolver=letsencrypt"
